---
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
  bookdown::word_document2: default
  bookdown::html_document2: default
params:
  corrections: true
bibliography: 
  - bibliography/references.bib
bibliography-heading-in-pdf: Works Cited
documentclass: book
---

# Introduction {#chapter-introduction}

\adjustmtc 

\mccorrect{!TODO[Style notes]}: 

* Graphs and stats:  
    * Continuous axes which show theoretical limits should have small expand, axes which do not show those limits should have arrowheads from broken_axis_*  
  
  * mccorrect -> resolve issues
  
\mccorrect{TODO: Check R output messages, warnings, errors}

\mccorrect{Search final output for ()}


Animals (and possibly other organisms) make decisions continually.
They need to decide how to act, often on the basis of judgements on the state of the world.
The average person will make hundreds of conscious decisions a day, and thousands of unconscious ones: what do I want for breakfast?; do I take an umbrella?; what should I get my child for their birthday?; is that other pedestrian going to bump into me?; and so on.
Crucially, for many of these decision-makers, useful information can be obtained from other people: seeing what other diners are having in a restaurant; listening to a meteorologist forecast the weather; paying attention to your child's insistent requests.
This kind of social information suffuses the world of human decision-making, and so too do judgements about its usefulness.

To use social information appropriately, people need to know whether the information is useful for them: it may be a mistake for someone looking for a lavatory in a theatre to join the longest queue on the assumption that it indicates the most popular choice.
Beyond misinterpretation, there is the ever-present threat of duplicity: the history of cooperation is inextricably entwined with the history of free-loading, cheating, and deception.
Who we trust, and how far, is a matter of great practical importance.
This thesis investigates two questions in this area: whether we rely too much on those similar to us, and whether we rely too little on others in general.

Two key ideas in social influence concern echo chambers and egocentric discounting.
Echo chambers are social environments where only one opinion is able to exist: everyone within the echo chamber expresses the same opinion, an opinion that is then 'echoed' back to them by others, making it appear ubiquitous and certain.
Egocentric discounting is the name for the general observation that people do not use information from others as efficiently as they could.

This thesis explores two questions related to those ideas: does the way individuals seek advice produce echo chamber-like networks?; and is the well-established phenomenon of people 'irrationally under-weighting' advice actually explicable as a rational process?
The first of these questions concerns how people learn about the trustworthiness of others who give them advice, especially where they have no objective way of knowing how useful that advice actually is.
I ask whether people are more likely to seek advice from others whom they consider more trustworthy, and whether this might lead to forming echo-chambers full of like-minded individuals who assess one another as trustworthy because they parrot their own opinions back again.
This question is addressed using on-line empirical behavioural experiments to characterise the individual psychological processes underlying advice seeking, followed by agent-based computational simulations that implement the variation in those processes observed in human participants.

The second question takes as its starting point the observation that people do not take as much advice as they _should_ (as defined by a mathematical model of information). 
There has been much discussion concerning the reasons for this, and I develop a contribution to this debate; the suggestion that most of the time it really is better to take a cautious approach to advice-taking to avoid being too vulnerable to ignorance, malice, and miscommunication.
The question is addressed using computational agent-based evolutionary simulations to explore the adaptiveness of discounting advice under a range of circumstances.
I then explore people's flexibility in responding to changes in those circumstances using on-line behavioural experiments.
The organisation is as follows: this introduction establishes the core concepts invoked in this thesis, and describes their treatment in the literature.
Then, the two questions are addressed in separate sections of the thesis. Each section includes a short introduction to the specific question addressed, a detailed description of the work conducted, and a short discussion of the conclusions drawn from the work.
The final section offers broader conclusions arising as a consequence of the presented work, alongside some suggestions for future research.

In the remainder of this introduction, I introduce the key concepts that arise in the thesis.
First, I introduce advice and highlight relevant features, including the measurement paradigm used in this work and a normative model that quantifies how advice _should_ be used.
Second, I briefly introduce the phenomena of interest.
Finally, I develop the normative model with ideas of use of advice and advisor evaluation to form the framework within which the experiments and simulations take place.

## Advice 

Advice can be broadly defined as information which comes from a social source.
Defined this way, it includes things most people would intuitively understand as advice, such as guidance from a mentor or lawn care tips, and things most people may not, such as advertisements, traffic, and recommender algorithms in on-line shops.
Advice is different from other sources of information, such as the forbiddingness of a storm cloud or the rattle of a rattlesnake, in that it is the result of human mental processing of other information.^[There are of course cases that defy this categorisation: for example, it seems uncontentious to allow that Honey Guides and Guide Dogs offer advice to their human counterparts.]
In some cases, it may additionally include discussions among different group members (e.g.
advice from the International Advisory Panel on Climate Change).

Throughout this thesis, the focus is primarily on advice which comes from a single, stable source, as when we see a post by an acquaintance on social media, or when a stranger provides us with advice.
This is generally within the marrow of what is understood by "advice", and the aim of the investigations herein are to shed light on the way humans exchange information with one another and the consequences of those exchanges.

### Advice-taking

Advice occurs in the context of a decision, and forms a part of the information which is integrated during the decision-making process to produce a decision.
To the extent that the decision reached differs from the decision that would have occurred had the advice not been presented, the advice has had an effect on the decision; to the extent that this difference changes the decision in a way consistent with the advice, the advice has been 'taken' (as opposed to 'rejected').

It is tacitly implied by many operationalisations of advice-taking that the informational content of the advice determines the extent to which it is taken or rejected.
For example, _weight on own estimate_ and its derivatives quantify advice-taking as the amount an opinion is updated in the direction of advice [@yanivAdviceTakingDecision2000].
Insofar as the identity of the advisor matters, it matters because it functions as a cue to the informational content of the advice -- for example where advice is more likely to be correct because it comes from someone with expert knowledge rather than someone who is guessing.
This is likely a major oversimplification, however, because in many real-world contexts advice-giving and advice-taking form part of a developing social relationship: being consulted for advice and having one's advice followed are inherently rewarding [@hertzIntrinsicValueSocial2018; @hertzNeuralComputationsUnderpinning2017]; and taking advice can serve as a (sometimes costly) social signal of valuing a relationship with a person or group [@byrneOstracismReducesReliance2016].
Furthermore, some authors have argued that people may perceive taking advice as sacrificing their independence or autonomy [@raderAdviceFormSocial2017; @ronayneWhenGoodAdvice2018].
While this thesis follows previous literature in omitting to consider the wider social concerns influencing the taking of advice, it is nevertheless important to remember that the processes investigated herein take place in a variety of social contexts where complex social agents attempt to optimise over numerous goals over numerous time-scales.

### Three-factor model of trust

The degree to which advice is taken is proportional to the trust placed in the advisor by the decision-maker.
Interpersonal trust, or the degree to which one is prepared to place one's fortune in the hands of another (e.g.
by relying on their advice), is apportioned by @mayerIntegrativeModelOrganizational1995 onto three properties of the advisor (as judged by the decision-maker): ability, benevolence, and integrity.
To these three properties of the advisor we may add the decision-maker's general propensity to trust, as well as situational cues and task cues (e.g. the phenomenon that advice is more readily taken for hard tasks than easy ones, [@ginoEffectsTaskDifficulty2007; @yonahTheyDonKnow2021]).

#### Ability {#i-ability}

Ability captures the expertise of an advisor: their raw ability to perform the task for which they are giving advice.
In some cases this is relatively straightforward, as in the expertise of a General Practitioner in matters of health and disease, and in others more complex, as in the expertise of a hairdresser when deciding on a haircut (when matters of personal taste comingle with aesthetic considerations of facial structure, practical considerations of hair constitution, and social considerations of fashion).
The greater the ability of an advisor, the greater the influence of their advice, as demonstrated by experiments showing that participants' decisions are more affected by the advice of advisors who are labelled as more expert in a relevant domain [@sahCheapTalkCredibility2013; @schultzeInabilityIgnoreUseless2017; @sniezekImprovingJudgementPrepaid2004; @sniezekTrustConfidenceExpertise2001; @sollJudgmentalAggregationStrategies2011], or are shown to be more expert empirically [@pescetelliRoleDecisionConfidence2021; @sahCheapTalkCredibility2013; @yanivAdviceTakingDecision2000].

#### Benevolence

Benevolence refers to the extent to which the advisor seeks to further the interests of the decision-maker.
Where ability represents the absolute limit on the quality of advice, benevolence represents the extent to which the advice approaches this limit.
The advice of even a renowned expert may be doubted if there is reason to believe their goal is to mislead, a vital lesson for medieval monarchs with their councils of politicking advisors.
Experimental work has shown that participants are more inclined to reject advice when uncertainty is attributed to malice rather than ignorance [@schulInfluencesDistrustTrust2015].

#### Integrity

Advisors with integrity exhibit adherence to principles which the decision-maker endorses.
"Integrity" in this sense is related to the common-use sense of integrity as following a code or set of principles unwaveringly, but with the caveat that the principles have to be ones shared with or respected by the decision-maker. 
To borrow an example from @mayerIntegrativeModelOrganizational1995, a ruthless dedication to "profit seeking at all costs" would lead to an advisor being highly mistrusted, except where the person doing the trusting also endorsed that value.
While benevolence and integrity are not mutually exclusive, integrity is typically important where relationships are less personal (e.g. we may place great trust in a General Practitioner because of their expertise in medical matters and their integrity in adhering to a set of professional ethical and conduct requirements).
In many cases, integrity is difficult to disentangle from ability, because subscription to values often indicates a knowledge of a domain, which can act as a cue for ability.
Where professional societies are involved, for example, many require formally-recognised training for membership.
Providing a concise and accurate definition of integrity, complete with appropriate qualifiers and explanations, is well beyond the scope of this thesis: integrity has long suffered from conceptual confusion and disagreement between researchers [@palanskiIntegrityLeadershipClearing2007], with recent consensus perhaps emerging that it is best understood as a multi-dimensional construct [@moormanUnderstandingHowPerceived2018] that may or may not bear close resemblance to the construct imagined by @mayerIntegrativeModelOrganizational1995.

Within the scope of this thesis, integrity can be thought of as a commitment to fulfilling one's role in an experiment, in the case of advisors giving advice according to stated goals (usually doing one's best to help the decision-maker). 
In combination with benevolence, integrity acts to determine the extent to which the helpfulness of advice approaches the limit imposed by the advisor's ability.

### Source selection and advice-taking

From the perspective of this thesis, the two key components of advice are its source and its informational content.
The underlying framework§\@ref(i-framework)^[See section \@ref(i-framework). Throughout the thesis, internal links are abbreviated in this manner.] used here views the informational content of advice as providing information not only about the external world and the best way to act, but also as providing information about the source of advice itself.
Both the advice itself and information about its source can contribute to the likelihood of the advice being incorporated into a final decision.
The literatures on source selection (where we look for advice) and advice-taking (how we use advice when it is provided) are grounded in different academic traditions.
Source selection is usually studied within the context of Social and Personality Psychology, with choices viewed as minimising cognitive dissonance [@festingerTheoryCognitiveDissonance1957] or protecting a positive self-concept [@knobloch-westerwickSelectiveExposureSelf2015].
Advice-taking, on the other hand, is formally investigated in the Organisational and Cognitive Psychology literatures on judgement and decision-making and forecasting, and frames behaviour with reference to normative models§\@ref(i-normative).

In this work, I take steps towards joining these literatures by extending a framework for advisor evaluation in the absence of feedback§\@ref(i-framework) to the domain of source selection, referred to here as advisor choice.
This thesis thus uses an approach more similar to the advice-taking literature than to the source selection literature.

### Judge-advisor system

The paradigm used for the behavioural experiments and as a framing for the computational simulations is a Judge-Advisor System [@yanivAdviceTakingDecision2000; @sniezekImprovingJudgementPrepaid2004].
In this paradigm, two or more individuals contribute to making a decision, one as the judge and the other as the advisor.
The judge makes an initial estimate alone, then receives advice from the advisor, and then makes a final decision integrating the advice with their initial estimate as they see fit.
This paradigm allows advice to be quantified on the assumption that any systematic differences between initial estimates and final decisions are properties of the advice.

In theory, any decision-making task can be used for a Judge-Advisor System provided it allows for the judge to make two decisions and advisors to provide plausible advice.
Estimation tasks are commonly-used in the literature, such as estimating life expectancies in difference countries [@troucheVigilantConservatismEvaluating2018], the dates of historical events [@yanivAdviceTakingDecision2000], the price of an item from its features [@sniezekImprovingJudgementPrepaid2004], people's weights [@ginoEffectsTaskDifficulty2007], sports teams' performances [@sollJudgmentalAggregationStrategies2011], opinion prevalence rates [@libermanNaiveRealismCapturing2012], and calorie values of foods [@yanivExploitingWisdomOthers2012].
Other studies have used perceptual estimation tasks requiring visual perceptual decisions about displays of dots [@pescetelliRoleDecisionConfidence2021; @rouaultFormingGlobalEstimates2019], or the presence or absence of a visual target [@mahmoodiEqualityBiasImpairs2015]; these tasks have less obvious ecological validity but afford precise experimental control of participants' performance and advice accuracy.
The behavioural experiments in this thesis use historical date estimation and perceptual dot-discrimination tasks. 

### Normative models of advice-taking {#i-normative}

Advice-taking can be evaluated formally with reference to a normative model.
The simplest and most common of these views the decision-making task as an estimation problem (or combination of estimation problems), and provides an approximately Bayesian variance-weighted integration of independent estimates.
To borrow from Galton [-@galtonVoxPopuliWisdom1907]}, consider the task of judging the weight of a bullock.
We can model any single guess ($i$) as the true weight ($v$) plus some error ($\epsilon$):

\begin{align}
i &= v + \epsilon \\
\epsilon &= \mathcal{N}(\mu=0,\,\sigma^{2})
(\#eq:estimate)
\end{align}

The key insight is to observe that the error is drawn from a normal distribution (Equation \ref{eq:estimate})[^symmetrical-distribution].
As the number of samples from this distribution increases, the mean of those samples tends towards the mean of the distribution.
Thus, the more estimates are taken, the closer on average the sum of errors will be to 0.

\begin{align}
\frac{\sum_{a}^{N}(i_{a})}{N} &= \frac{\sum_{a}^{N}(v + \mathcal{N}(\mu=0,\,\sigma^{2}_{a}))}{N}\\
\frac{\sum_{a}^{N}(i_{a})}{N} &= \frac{\sum_{a}^{N}(v)}{N} + \frac{\sum_{a}^{N}(\mathcal{N}(\mu=0,\,\sigma^{2}_{a}))}{N}\\
\frac{\sum_{a}^{N}(i_{a})}{N} &= \frac{Nv}{N} + \hat{0}\\
\frac{\sum_{a}^{N}(i_{a})}{N} &\approx v
(\#eq:wisdom-of-crowds)
\end{align}
<!-- Could extend the above to include individual bias ($\mu_{i}$).
This could then be used to show that correlated biases produce systematic distortions in the estimates, with the point that correlated biases differ from correlated error in that error is by definition due to chance while bias endures throughout repeated interactions.
-->

Observe that this formulation is true no matter the value of $N$.
On average, it is always better to have more estimates than fewer, because as the number of estimates increases the sum of their errors approaches 0.
Even in the situation where there are only two estimates (the decision-maker's and the advisor's), the best policy will be to incorporate both estimates into the final decision.

Where variances of the error distributions are known ($\sigma^{2}_{i}$), estimates can be weighted by those variances:

\begin{align}
f = \frac{\sum_{a}^{N} (\omega_a i_a)}{\sum_a^N \omega_a}
(\#eq:variance-weights)
\end{align}

Where $\omega_a$ is $1/\sigma^2_a$.
This will increase the accuracy of the estimates in proportion to the difference between the variances.

Many experimental implementations of this model avoid weighting issues by calibrating judges (decision-makers) and advisors to be equally accurate on average ($\sigma^{2}_{\text{judge}}=\sigma^{2}_{\text{advisor}}$).
The result of this constraint is that the optimal policy is simply to average all estimates together:

\begin{align}
f &= \frac{\sum_a^N (i_a)}{N} \\
&\approx v
(\#eq:optimal-averaging)
\end{align}

This framework provides a formal basis for understanding and assessing how information is integrated in social and group scenarios.
As a normative model, the framework provides an optimal strategy for using advice by modelling how advice can improve a decision-makers accuracy.
Additionally, the framework formalises the notion of the "wisdom of crowds" -- the observation that groups can often come to decisions that are better than the best individual's decision.
Below, I show how this framework extends to cover the use of advice where agents have systematically different capabilities§\@ref(i-use).

[^symmetrical-distribution]: The normal distribution is well-supported by empirical evidence, but note that any symmetrical distribution around 0 will lead to the same conclusion.

## Advice-taking phenomena

This work is primarily interested in two advice-taking phenomena, one in which people weigh advice too heavily, and one in which people weigh advice too lightly.
In one of these, people form echo chambers in which they are over-reliant on the advice of those like themselves, leading to missed opportunities to make accurate assessments.
In the other, egocentric discounting, people take less advice than they should, according to the normative model presented above§\@ref(i-normative) when integrating multiple opinions with their own.

### Homophily and echo-chambers

Homophily is the ubiquitous phenomenon that individuals more closely connected to one another within a social network tend to be more similar to one another than would be expected by chance across numerous dimensions, from demographics to attitudes [@mcphersonBirdsFeatherHomophily2001].
@mcphersonBirdsFeatherHomophily2001 review a wealth of examples, including the tendency for married couples to be more similar to one another than chance would dictate in their ethnicity, age, and religion (and along many other dimensions).
The use of homophily as a concept has increased dramatically in the last few decades, across a range of different research fields.
Different fields (and researchers) provide different measurements, such as asking people to nominate their friends and comparing demographic information [@mccormickFeasibleRigorousRelevant2015] or comparing social media users' content similarity and interactivity [@cardosoTopicalHomophilyOnline2017], but the unifying idea is that more similar individuals are more likely to have closer contact with one another [@lawrenceHomophilyMeasuresMeaning2020].

Homophily is often discussed negatively, especially in the context of ethnic differences and intergroup tensions [@mcphersonBirdsFeatherHomophily2001], but in many contexts it is not only expected but desired.
Homophily on the basis of shared interests is unavoidable: provided people spend time doing things they are interested in, for example playing a sport, they will tend to spend time with other people doing those things.
Similarly, many romantic matchmaking services deliberately use similarity on dimensions such as age to identify likely partnerships.
Due to association between the many dimensions in which homophily operates, such as ethnicity and religion, it is often difficult in practice to separate out the dimensions along which homophily is operating.

Social influence processes combine with homophily to create a self-reinforcing spiral: individuals who are more similar to one another are more likely to associate with one another; and individuals who associate with one another are more likely to become more similar to one another.
Again, this can be benign, as when newcomers to a social group are welcomed and absorb the social norms of interaction.
Where this cycle generates concern is when reciprocal influence produces increasingly extreme attributes, for example political opinions.
This process is known as "polarisation".

Polarisation is the phenomenon whereby the distribution of opinions in a population trend toward extremes over time, with moderate stances becoming increasingly less popular.^[There are a variety of precise and somewhat different definitions in the literature [@bramsonDisambiguationSocialPolarization2016].] 
Polarisation can be one-way, as when a consensus forms on a topic and that consensus shifts the entire ground of the debate (as with the core feminist principle that women and men deserve equal respect), or two-way as with divisive issues like the suitability of former President Donald Trump for office.
While in both cases the whole population has acquired an extreme opinion, in the former the population remains united whereas in the latter the population is deeply divided, with little middle ground.

Theoretically, homophily may lead to polarisation because it isolates people from the checks and balances of the real world.
Within an echo chamber inhabited by those who have similar values, experiences, and opinions to ourselves, it becomes easy to miss the drawbacks to new ideas.
We receive positive feedback for opinions of a certain stripe, and join in with applauding them when we hear them.
More extreme ideas in keeping with the views appear pioneering and courageous, while more moderate ideas become old-fashioned.

Most people who argue for the nefarious consequences of homophily and polarisation for society as a whole highlight social media, and the fluency of association that it offers, as a catalyst that sweeps away many traditional checks to the vicious cycle of homophily and polarisation.
Whereas in the physical world we can only interact with those nearby, in the on-line world we can interact with people anywhere in the world, meaning we can find people whose opinions are far more similar to our own along far more dimensions [@daviesTwinImpactHomophily2017].
Added to this, the algorithms that curate content on dominant social media platforms prioritise emotive content, selecting extremes of opinion to be reviled or applauded, and replacing the previously universally-shared culture with a culture shared only by our echo chamber [@sunsteinRepublicCom2002; @sunsteinRepublicDividedDemocracy2018]. 
Modelling work demonstrates that where there is a bias in assimilation of information, homophily exacerbates polarisation [@dandekarBiasedAssimilationHomophily2013].
Where polarisation in turn increases homophily, for example through selective exposure (where individuals seek out reinforcing views) or avoidance (where individuals avoid challenges to their views), a self-reinforcing spiral emerges wherein social connections become increasingly homogeneous and attitudes increasingly extreme [@songDynamicSpiralsPut2017].

Despite this compelling picture, whether homophily in on-line social networks actually _is_ responsible for increases in polarisation is debated.
Proponents of the idea note that political polarisation has increased in recent years [@perrettDividedKingdomVariation2021; @boxellGreaterInternetUse2017]; opponents note that this is not a new phenomenon [@perrettDividedKingdomVariation2021] and that the sections of society polarising most rapidly are the least likely to use social media [@boxellGreaterInternetUse2017].
Experimental investigation has shown that corroboration may increase the extremity of opinions [@baronSocialCorroborationOpinion1996; @schkadeWhenDeliberationProduces2010], and this may outweigh the mollifying effect of contradiction [@lordBiasedAssimilationAttitude1979]; but @gronlundDoesEnclaveDeliberation2015 found decreased extremism of opinion among anti-immigration participants after group discussion.
Empirical studies demonstrate homophily in on-line social networks [@cardosoTopicalHomophilyOnline2017; @colleoniEchoChamberPublic2014]; but @barberaHowSocialMedia2015 argue that these social networks are _less_ homophilic than their off-line equivalents, and hence should _reduce_ polarisation.
There are many egregious examples of pathologically polarised insular on-line communities, but these are either pre-existing groups that have moved on-line (such as creationist communities), or new groups with deep similarities to old ones (such as Q-Anon and previous conspiracy theorist communities). 
Selective exposure is a potential driving mechanism for polarisation [@kobayashiSelectiveExposurePolitical2009]; although criticism of the idea goes back a long way [@searsSelectiveExposureInformation1967] and the emerging consensus among researchers seems to be that while individuals may preferentially seek out reinforcing information they are unlikely to selectively avoid information that would challenge their views [@garrettEchoChambersOnline2009; @garrettPoliticallyMotivatedReinforcement2009; @nelsonMythPartisanSelective2017].

The discrepancies between computational models that demonstrate polarisation and empirical evidence that paints a mixed picture may be due to people's tendencies for selective exposure and selective assimilation of information being lower than those assumed by the models. 
Inter-individual variation may also contribute to this puzzle.
This thesis explores biased source selection, its heterogeneity, and their impact on the way information flows through social networks.

### Egocentric discounting

From the perspective of the normative model above§\@ref(i-normative), decision-makers should weigh their own estimate equally with each other estimate they receive in the process of coming to their decision.
This is because the errors in the judgements made by the decision-maker and the advisors are interchangeable, mathematically-speaking, and on average one will approximate the correct answer most nearly by allowing all of the errors to cancel one another out, which is achieved by averaging across all estimates as show in Equation \ref{eq:wisdom-of-crowds}.
However, one of the most robust findings in the literature on advice-taking is that people routinely under-weight advisory estimates relative to their own estimates, a phenomenon known as _egocentric discounting_[@danaAdviceChoice2015; @ginoEffectsTaskDifficulty2007; @hutterSeekingAdviceSampling2016; @libermanNaiveRealismCapturing2012; @minsonCostCollaborationWhy2012; @raderAdviceFormSocial2017; @ronayneIgnoringGoodAdvice2018; @seeDetrimentalEffectsPower2011; @sollJudgmentalAggregationStrategies2011; @troucheVigilantConservatismEvaluating2018; @yanivAdviceTakingDecision2000; @yanivExploitingWisdomOthers2012; @yanivUsingAdviceMultiple2007].

@yanivAdviceTakingDecision2000 provided a classic example of egocentric discounting in a task that required participants to provide initial estimates of historical dates (e.g. "When were the Dead Sea Scrolls first discovered?"), and then provide final decisions of the same after seeing advice (taken from a random participant's answer in a previous study).
Despite both the initial estimates and the advice estimates being similarly accurate, participants' final decisions were much closer to their initial estimates than to the advice.
Instead of producing decisions that were midway between the two estimates, as would be achieved with mathematically optimal averaging, participants weighted their initial estimate about 70:30 with the advice they received.

Egocentric discounting occurs in both feedback and no-feedback contexts [@yanivAdviceTakingDecision2000].
Explanations for egocentric discounting are usually framed in terms of personal-level psychology: decision-makers have better access to reasons for their decision [@yanivAdviceTakingDecision2000]; overrate their own competence [@sniezekImprovingJudgementPrepaid2004]; may have a desire to appear consistent [@yanivUsingAdviceMultiple2007]; may see opinions as possessions [@sollJudgmentalAggregationStrategies2011]; may be loss-averse to providing a worse fnitial decision due to advice-taking [@sollJudgmentalAggregationStrategies2011]; or have difficulty avoiding anchoring [@schultzeInabilityIgnoreUseless2017] or repetition bias effects [@troucheVigilantConservatismEvaluating2018].
None of these explanations has survived rigorous empirical testing, however, and recently suggestions have widened to include consideration of aggregate-level rather than personal-level causes, with @troucheVigilantConservatismEvaluating2018 arguing that the potential for misaligned incentives between decision-maker and advisor motivate discounting of advice.
The latter part of this thesis§\@ref(chapter-advice-taking-context) explores whether egocentric discounting may be a stable meta-strategy which protects against exploitation, carelessness, incompetence, and miscommunication.
From this perspective, the normative model is only normative within the very particular scenario it describes.
When we broaden the scope to consider how that particular scenario fits into a background of advice-taking in humans as the product of genetic and cultural evolution and individual experience, we find that the normative model must be altered to account for these features.

## Conceptual framework {#i-framework}

How seriously advice is taken is a consequence of how much a judge trusts it.
The framework underlying this thesis regards advice as being evaluated according to two key properties.
The first of these is the _content_ of the advice itself, i.e. how plausible it is given other evidence.
The second property is the _source_ of the advice, i.e. how trustworthy the judge considers the advisor to be.
Thus, while we might trust a friendly-looking stranger as much as a meteorologist when they opine that the sunshine will hold out for the rest of the afternoon, we might be much more likely to trust the meteorologist if the forecast is that the blazing sunshine will turn into a thunderstorm.

Our framework additionally proposes that the reputation of a source of advice is built up over time as a function of the advice that the source provides.
There are numerous factors that contribute to an advisor's trustworthiness, such as sobriety and professional expertise, and many of these can change over time, but this framework focuses on reputation as a function of advice quality.
Reputation roughly captures the @mayerIntegrativeModelOrganizational1995 dimension of _ability_, although it can incorporate other dimensions, too.
The mechanism of trust updating differs slightly according to the availability of objective feedback.

In the case where advice is given on a task that has an immediately-verifiable answer, the utility of the advice can be evaluated on the basis of feedback and the evaluation of the advisor updated accordingly.
If I am trying to remember whether I left my phone in my coat or my bag, and my partner tells me that it is in my bag, a brief examination of one or both of the potential locations will not only find my phone but will also allow me to evaluate the accuracy of my partner's advice.
Over multiple interactions on these kinds of decisions, my partner will acquire a reputation in my mind as a relatively reliable or unreliable source of this kind of information.

Where feedback is unavailable, people may use their own sense of certainty as a yardstick for evaluating advice [@pescetelliRoleDecisionConfidence2021]: advisors who agree when one is confident are perceived as more helpful; while those who disagree when one is confident are perceived as less helpful.
Perhaps instead of a lost phone, my partner gives me advice on the name of an old acquaintance of ours: although we cannot verify the information, if it 'rings a bell' I may be highly confident my partner is correct, and judge the utility of the advice accordingly.
In this way, confidence serves as a proxy for objective feedback.
Confidence functions well in this role insofar as the judge has high metacognitive resolution (i.e. higher confidence is indicative of a greater probability of being correct).

### Use of advice {#i-use}

Normative models of advice-taking§\@ref(i-normative) state that averaging estimates minimises errors.
As discussed at length later§\@ref(chapter-context), the assumptions underlying the normative model do not always hold in the real world, but this normative framework is a useful starting point for considering how advice can or should be used.
The performance of the normative model can be characterised according to differences between the advisor and the judge on ability and bias [@sollStrategiesRevisingJudgment2009], proving effective for the kinds of decisions on which the errors made by judge and advisor are independent of one another.
Equation \ref{eq:variance-weights} for our normative model states that advice should contribute to the final decision in proportion to the ability of the advisor compared to the judge.
In the two-estimate case (initial estimate and advice), this can be expressed as:

\begin{align}
f = \frac{\omega_a i_a + \omega_{a'} i_{a'}}{\omega_a + \omega_{a'}}
(\#eq:two-estimate)
\end{align}

Where agent $a$ is the judge, $i_a$ the judge's initial estimate, agent $a'$ is the advisor, $i_{a'}$ is the advice received (i.e. the initial estimate of agent $a'$), and $\omega_{a}$ and $\omega_{a'}$ the judge's weighting of their own and their advisor's answers, respectively.
This weighting can be simplified to be expressed only in terms of the judge's weighting of the advisor because the two are constrained to sum to 1 by virtue of being relative to one another:

\begin{align}
\omega_a + \omega_{a'} &= 1 \\
\omega_{a'} &= 1 - \omega_a \\
\therefore f_a &= (1-\omega_{a'}) i_a + \omega_{a'} i_{a'}
(\#eq:simply-weights)
\end{align}

In the normative model, the weighting is equivalent to the ratio of variance of the errors made by each agent:

\begin{align}
\omega_{a'} = \frac{\sigma^2_{a'}}{\sigma^2_{a'} + \sigma^2_a}
(\#eq:m-weight-by-variance)
\end{align}

The normative model thus represents weighting by relative ability.
Precise knowledge of the ability of others relative to oneself is rarely available in the real world, however, and, as discussed later§\@ref(chapter-context), other assumptions concerning the trustworthiness or interpretability of advice may be violated.

The normative model can be adapted to provide a more psychologically-realistic account of advice usage by substituting the three factor model of trust§\@ref(three-factor-model-of-trust) into the equations in place of the ability variable.
We start with the statement within the three factor model that trust ($\omega$) is proportional to $\text{ability}$, $\text{benvolence}$, and $\text{integrity}$.

\begin{align}
\text{trust} \propto \text{ability} \cdot \text{benvolence} \cdot \text{integrity}
(\#eq:m-three-factor)
\end{align}

We can thus replace the measure of accuracy in the normative model with the measure of trust in order to calculate the relative weighting:

\begin{align}
\omega_{a'} = \frac{\text{trust}_{a'}}{\text{trust}_{a'} + \text{trust}_a}
(\#eq:m-weight-by-trust)
\end{align}

At this point we may question whether the variable $\text{trust}_a$ (i.e., trust in one's own opinion) is a meaningful property or simply an artefact of mathematical symbol manipulation.
Mathematically it provides a fixed point against which trustworthiness of advisors can be measured, allowing for scaling weightings meaningfully across different advisors in different decisions.
In real world terms, while it is generally unlikely that $\text{benevolence}_a$ and $\text{integrity}_a$ will be anything less than maximal, perceptions of one's own ability ($\text{ability}_a$) are likely to allow for others to exceed it.
I make no strong claims on the relationship between trust and its component variables other than proportionality, and within this conception it is meaningful to consider weighting as a property of trust in another's judgement relative to one's own, adjusted in some manner for the perception of that other's benevolence and integrity:^[If the concept of self-trust still appears untenable, note that $\text{trust}_a$ can be replaced with a constant without compromising the equations.]

\begin{align}
\omega_{a'} &\propto 
  \frac{\text{ability}_{a'} \cdot \text{benvolence}_{a'} \cdot \text{integrity}_{a'}}
  {\text{ability}_{a'} \cdot \text{benvolence}_{a'} \cdot \text{integrity}_{a'} + \text{ability}_a \cdot \text{benvolence}_a \cdot \text{integrity}_a} \\
&\propto 
  \frac{\text{ability}_{a'} \cdot \text{benvolence}_{a'} \cdot \text{integrity}_{a'}}
  {\text{ability}_{a'} \cdot \text{benvolence}_{a'} \cdot \text{integrity}_{a'} + \text{ability}_a}
(\#eq:m-weight-expand)
\end{align}  

This model fits well with the variables manipulated throughout this thesis: increases in task difficulty and decreases in subjective confidence will alter the perception of $\text{ability}_a$, leading to greater advice-taking.
Likewise, increases in perceived benevolence, integrity, or ability of an advisor will lead to greater advice-taking.

#### Critique of the aggregation model

This conception of advice-taking as a weighted aggregation process between an initial estimate and advice underpins both the modelling and the experiments presented in this thesis.
It is thus worth taking a little space to highlight areas in which this model is known to depart from reality so that the work presented in this thesis can be judged and interpreted within its limitations.

Firstly, the model is an idealised situation approximated by the experimental method§\@ref(judge-advisor-system): a judge makes an explicit initial estimate, then receives advice, then makes an explicit final decision.
@yanivExploitingWisdomOthers2012 showed that preventing judges from making initial estimates resulted in very different advice weighting, suggesting that this may be a model of a specific scenario rather than of advice integration per se.
The model presented here could in principle explain an integration process where an initial estimate can only be made after the advice is known, but empirically performs poorly.
At best, it could be argued that pre-exposure to the advice either anchors the initial estimate (thus moving $i_a$ systematically closer to $i_{a'}$), or that having to trust advice because one cannot make one's own decision inflates the weighting of the advisor.

Secondly, the model does not perform well when multiple advisors are consulted.
The normative model, and the psychological derivative, predicts that a judge's estimate ought to be weighted in conjunction with the other estimates.
In other words, as the number of advisory estimates increases, the weight of the initial estimate should decrease.
@hutterSeekingAdviceSampling2016 presented evidence that this does not happen: the weight of the initial estimate stays relatively constant while the weights of the advisor estimates are reduced.
This implies that if a judge were to average evenly their initial estimate with an advisor estimate ($\omega_i = .5$; $\omega_j = .5$), adding an extra advisor estimate would result in the weights of the advice being halved while the weight of the initial estimate remained constant ($\omega_i = .5$; $\omega_{j \neq i} = .25$), rather than the more transparently optimal policy of weighting all estimates evenly ($\omega_i = \omega_{j \neq i} = 1/3$).
Similarly, @yonahTheyDonKnow2021 showed that, while increasing the number of advisors from whom an estimate is drawn from 20 to 200 does increase the weight placed on advice a little, it is nowhere near the level that would be expected normatively.

Finally, the model is supported by experiments that present advice-taking in terms of averages over several trials.
These averages can obscure very different behaviours on a trial-by-trial basis: the same average advice weight of 50% would appear for a set of trials where initial estimate and advice were consistently evenly weighted as well as for a set of trials where the judge alternated between keeping their initial estimate and wholly adopting the advice.
Analysis of individual trials shows that the aggregate patterns of advice-taking appear to be roughly distributed between an averaging strategy and a picking strategy, whereby one or other answer is wholly adopted [@sollJudgmentalAggregationStrategies2011; @sollStrategiesRevisingJudgment2009].
The model, derived from these patterns, approximates the contribution of an individual trial to the overall average rather than the actual advice-taking strategy on any given trial.

The model could be extended to incorporate this distinction between picking and averaging behaviour by building in an additional parameter governing the likelihood of picking as opposed to averaging on a given trial.
In the present model these two potential parameters, whether to pick or average and how much to average, are collapsed into one parameter governing the extent of averaging.
Such additional complexity is not warranted here, but I highlight the distinction to allow readers to consider for themselves.

#### Justification for use of the aggregation model

The criticisms above are important, but they do not invalidate the model for use in the present project.
This work seeks to establish how differences in advice-taking manifest according to properties of advisors.
These differences are well characterised by the model, especially in the judge-advisor system used for the experiments.
All models are inexact descriptions of reality, and inclusion of a more complex model capable of handling the cases outlined above would require greatly increased complexity for relatively little gain in explanatory power.
For studying the questions at hand, the psychological model is an appropriate and useful approximation of human behaviour.

### Updating advisor weights

The weights assigned to the advisors (relative to the judge themself) are subject to change as the result of experience.
This experience can be exogenous or endogenous to the decision-making task.
In the exogenous case, advisors may be labelled in a particular way [@onkalEvaluatingExpertAdvice2017; @tostPowerCompetitivenessAdvice2012; @schultzeInabilityIgnoreUseless2017] or have some summary of their performance displayed [@ginoAnxietyAdviceAbility2012; @yanivAdviceTakingDecision2000].
Endogenous experience refers to the information that advice on a given trial carries about the trustworthiness of an advisor, and forms the basis of the @pescetelliRoleDecisionConfidence2021 model used here.

Endogenous experience of advice means that the weighting of an advisor is in part dependent upon the past advice offered by that advisor.
As each piece of advice is evaluated, the overall weighting of the advisor is updated accordingly.
For clarity, two simplifiying assumptions are made in the explanation below.
Firstly, while it is probable that properties of the advice are used to inform the dimensions of ability, integrity, and benevolence simultaneously, the examples below will deal with ability in isolation.
Another project could explore in detail how experience of advice on any given trial updates an advisor's position in 3-dimensional trust space in a Bayesian manner according to the relative certainties about each dimension.
This would capture the task of assigning blame for erroneous advice (e.g. was it unintentionally poor - a failure of ability - or deliberately misleading - a failure of benevolence?).
Such an undertaking is beyond the scope of this project; in this thesis only cursory attempts are made to manipulate perceptions of dimensions other than ability (e.g. Experiments 5§\@ref(be-dba) and 6§\@ref(be-dbc)).

Secondly, it is assumed that advice is judged on its own merit as an estimate rather than on its usefulness as advice.
The former means that advice is assessed in terms of the optimality of the decision recommended by the advice itself.
The latter assesses advice based on the optimality of the decision based on advice relative to the optimality of the decision which *would have been made had the advice not been received*.
People may alter their advice-giving behaviour in anticipation of discounting on the part of the judge [@renaultDynamicSenderReceiver2013; @azariaStrategicAdviceProvision2016], somewhat akin to starting negotiations with a higher demand than one is hoping to settle for, in which case this assumption would not be wholly true.
There is no evidence as yet as to whether people do this, and whether judges anticipate and adjust for this adjustment on the part of the advisor.
For the questions considered here, conclusions obtained under these simplifying assumptions are likely to hold even when the additional complexity is restored.
The effects in the real world of interactivity between trust dimensions and game theoretic adjustments in the giving and interpretation of advice are likely to be small in comparison to general effects of advisor updating.

#### Evaluation of advice

A single piece of advice can be evaluated using its own properties and the properties of the advisor giving the advice.
Furthermore, that evaluation can serve to update the properties of the advisor.
A piece of advice's own properties will include its plausibility (e.g. participants in estimation tasks discount advice which is distant from their own initial estimates more heavily [@yanivReceivingOtherPeople2004]), while the properties of the advisor will include the advisor's trustworthiness (see above§\@ref(i-use)).
The updating of trust following experience of advice is likely to be largely in the domain of ability§\@ref(i-ability), although other domains may be affected where the advice is particularly egregious.

### Updating advisor evaluations

While a single piece of advice must be taken on its own terms, people can construct relatively accurate estimates of advisors' advice when provided with feedback on the decisions they use the advice to make [@pescetelliRoleDecisionConfidence2021; @sahCheapTalkCredibility2013; @yanivAdviceTakingDecision2000].
This likely happens as an analogue of reinforcement learning, where feedback allows an error signal to be used to update the estimate of the advisor's ability ($\widehat{\text{ability}}_{a,a'}$) rather than one's own beliefs about the world, according to some learning rate ($\lambda$).
\begin{align}
\widehat{\text{ability}}^{a,a'}_{t+1} = (1-\lambda) \cdot \widehat{\text{ability}}^{a,a'}_t + |i^{a'}_t - v_t|\cdot\lambda
(\#eq:advisor-evaluation)
\end{align}

#### Criticism of the advisor evalutation model

While many experiments have established the existence reinforcement learning in humans and other animals, it is unclear whether reinforcement learning operates in the social domain in which advising takes place.
It is not obvious that there are many situations in the course of everyday relationships which can be characterised by the rapid advice-feedback cycle required to learn about advisor ability in the manner modelled above.
@feldmanhallViewingAdaptiveSocial2019 argued in a review that a wide variety of social phenomena could be explained via reinforcement learning processes, and @behrensAssociativeLearningSocial2008 demonstrated that a Bayesian reinforcement learning model provided a good fit to behavioural data from a social influence task.
Additionally, @heyesKnowingOurselvesTogether2020 have argued that social learning is wholly explicable in terms of general reinforcement learning processes paired with attentional biases to social stimuli.
Reinforcement learning in the social domain operates on the basis of rapid feedback, just as in the non-social domain.
Below, the advisor evaluation model is extended to cases where objective feedback is not available by substituting the judge's confidence for objective feedback.
While not foolproof, the method allows better-than-average approximation of the quality of advisors provided several plausible assumptions are met [@pescetelliRoleDecisionConfidence2021].

### Advisor evaluation without feedback

Where feedback is not available, participants in experiments continue to demonstrate an ability to respond rationally to differences in advisor quality [@pescetelliConfidenceAdviceSeeking2021].
This is evidently not done through access to the correct real-world values, because feedback providing those values is unavailable, and, were participants aware of those values themselves, it stands to reason they would have provided those values (and thus not require advice!).
@pescetelliRoleDecisionConfidence2021 suggest the mechanism for this ability to discriminate between advisors in the absence of feedback is performing updates based on confidence-weighted agreement.

#### Agreement

Consider first the non-weighted agreement case, where the advisor's estimate ($i^{a'}_{t}$) and the judge's estimate ($i^a_t$) at time $t$ are binary ($\in0,1$).^[Where decisions are not binary, for example selecting between multiple options, the consequences of disagreement are less clear, but the qualitative insights concerning agreement hold.]
The estimate of the advisor's ability ($\widehat{\text{ability}}^{a,a'}$) is updated positively if the advisor and judge agree, and negatively otherwise, according to the learning rate $\lambda$.

\begin{align}
\widehat{\text{ability}}^{a,a'}_{t+1} = \begin{cases}
(1-\lambda) \cdot \widehat{\text{ability}}^{a,a'}_t + \lambda, & i^a_t - i^{a'}_t = 0 \\
(1-\lambda) \cdot \widehat{\text{ability}}^{a,a'}_t - \lambda, & i^a_t - i^{a'}_t \neq 0
\end{cases}
(\#eq:advisor-agreement-binary)
\end{align}

This agreement heuristic generally is quite useful: the likelihood of an independent other agreeing with you is monotonically related to their accuracy, so you can learn something about the accuracy of others simply by seeing how often they agree with you.
This holds provided you are more accurate than chance: if you are less accurate than chance then the more accurate an advisor is the more likely they will _disagree_ with you.
This is because the probability that you and your advisor agree depends on both their accuracy and your accuracy.

##### Confidence-weighted agreement

The insight that the usefulness of agreement as a proxy for accuracy scales with the judge's own probability of being correct means judges may be able to gain insights into that usefulness.
Judge's accuracy varies from decision to decision, and this variation means that some decisions are accurate (and hence agreement is a useful proxy for advisor accuracy) while others are inaccurate (and hence agreement is a poor proxy).
Insofar as a judge has insight into whether or not their decisions are more or less accurate, they have insight into whether or not agreement is a useful proxy for advisor accuracy.
The judge's own confidence in their decisions is a metacognitive signal that, for well-calibrated judges, can serve this purpose.

Thus, the updating of advice contingent on agreement may be weighted by confidence in the initial estimate ($c^a_t$), such that agreement and disagreement are considered more informative about the quality of the advice when the decision with which they agree or disagree is more certain.

\begin{align}
\widehat{\text{ability}}^{a,a'}_{t+1} = \begin{cases}
(1-\lambda) \cdot \widehat{\text{ability}}^{a,a'}_t + c^a_t \lambda, & i^a_t - i^{a'}_t = 0 \\
(1-\lambda) \cdot \widehat{\text{ability}}^{a,a'}_t - c^a_t \lambda, & i^a_t - i^{a'}_t \neq 0
\end{cases}
(\#eq:advisor-agreement-weighted-binary)
\end{align}

A well-calibrated judge who adopts this approach can thus exploit their insight into their own performance to improve their assessments of their advisors.
On those decisions where the judge is most likely to be correct they will be more confident, and will therefore (rightly) take agreement and disagreement to be more diagnostic of their advisor's ability.

### Use of the framework

This model of agreement-dependent advisor evaluation in the absence of feedback (whether confidence-weighted or non-confidence-weighted) forms the framework on which the experiments and computational models in this thesis are based. 
Framed in these terms, we can think of egocentric discounting as systematic under-weighting of advice from others relative to self, and ask why this might occur. 
We can think of echo chambers as systematically over-weighting advice from others who tend to agree, and explore why this occurs.

I present behavioural experiments that aim to explore the validity of this framework, and computational models that explore its implications. 
The behavioural experiments do not offer severe tests of the framework because they are primarily concerned with advisor choice: a lack of evidence for a preference between advisors on any given experiment may be explicable by a failure to translate a higher assessment of an advisor's advice into a preference for selecting that advisor rather than a failure to acquire a higher assessment of an advisor's advice.

### Thesis structure

Chapters 2-5 consider the psychology of advisor choice, asking how people choose advisors and how these choices impact network-level dynamics.
Chapter 2 introduces the general methodology used in the behavioural experiments and the analytical approach.
Chapter 3 extends previous behavioural experiment work on advice use to a new task.
Chapter 4 presents behavioural experiments that use both the previous perceptual decision-making task and the new general knowledge estimation task to investigate advisor choice.
Chapter 5 presents computational simulations guided by the results presented in Chapter 4 that explore the impact of individual-level advice-seeking and advice-taking tendencies on overall network dynamics.

Chapters 6-8 explore advice-taking more closely, asking whether under-weighting advice could be rationally motivated.
Chapter 6 reviews the literature on egocentric discounting, and introduces our perspective.
Chapter 7 presents computational simulations that illustrate the adaptiveness of egocentric discounting as a response to several plausible features of the advice-taking context.
Chapter 8 presents behavioural experiments that explore whether people can flexibly response to changes in the features modelled in Chapter 7.

Finally, Chapter 9 concludes the thesis with a short summary of results and interpretations.
The broader implications of the work are considered, alongside its generalisability and limitations.
