---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::html_document2: default
  bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
documentclass: book
---

# (PART) Interaction {-}
\minitoc <!-- this will include a mini table of contents-->

# Interaction of psychological processes across minds {#chapter-interacting-agents}
\adjustmtc 

* We saw in Section II that advisor choice is varied among individuals.

* We know from previous modelling work that source selection behaviour produces homophilic network dynamics (e.g. echo chambers).

* We wonder what the variability observed in Section II will have on network dynamics.

## Mini-review of networking models

* Niccolo showed source selection is pathological (unless judgements are uncorrelated) in absence of bias updating
  - True whether or not confidence weights updating
  
## Goals of this approach

* Characterise models which implement basic effects
  - Polarisation/attractors
  - Echo chambers (burn-in period)
  - Agents based on same model used for behavioural data
  
* Explore dynamics when using different values of weighted selection
  - Mean 0 vs mean derived from parameter estimation
  - Mean derived from parameter estimation vs Mean + SD derived from parameter estimation
  - Mean + SD derived from parameter estimation vs samping estimated values
  
## Limitations

* This is an initial exploration only
  - Models are time-consuming to run (even with key components written in C++)
  - Parameter space is huge and dynamics dependent upon parameter interactions
* But it should serve to highlight whether and how heterogeneity could matter for dynamics
* ...and indicate directions for further study

## Old stuff

<!-- Models suggest interactions between agents exascerbate problems, especially where source selection and info weighting combine. -->

\mccorrect{!TODO[extend the simulation/agreement-effects-analysis stuff a bit and it will fill this chapter out well.]}

* Even when biases don't change (Niccolo covered that), source selection on the basis of agreement is inherently pathological (unless judgements are uncorrelated).  
  - This is true whether or not confidence weights updating. 

* Why should we care if it's not changing biases (i.e. opinions?)  
  - because it reinforces final decisions through agreement instead of attenuating them through disagreement. 

* Our psychological mechanisms from Section II thus produce bad network effects when feedback is absent. 

* Can we relate the networks back to the advice-giving environments from Section III?

Models say this will go horribly wrong.
